on:
  push:
    branches: [master]
    
jobs:
  deploy:
    name: Deploy to Ec2 instance
    runs-on: self-hosted
    steps:
      - name: TO EC2 instance
        run: |
          npm install
          npm run build
          pm2 stop 0
          pm2 start 0
          pm2 save
      
