on:
  push:
    branches: [master]
    
jobs:
  deploy:
    name: Deploy to Ec2 instance
    runs-on: self-hosted
    steps:
      - name: TO EC2 instance
        run: |
          sudo npm install
          sudo npm run build
          sudo pm2 stop 0
          sudo pm2 start 0
          sudo pm2 save
      
